# Данный файл - шаблонная конфигурация CI/CD конвейера. Он может быть изменен по Вашему усмотрению. 
# Некоторые шаблоны требуют предварительной настройки перед запуском.
#
# Подробнее о синтаксисе можно узнать в документации:
# https://docs.gitflic.space/cicd/gitflic-ci-yaml
image: ubuntu:latest

stages:
  - build
  - test
  - deploy

variables:
  # Общие переменные
  APP_NAME: "my-awesome-app"
  TIMESTAMP: $(date +%Y%m%d%H%M%S)

build:
  stage: build
  script:
    - echo "Сборка приложения $APP_NAME"
    - echo "Текущее время $TIMESTAMP"

test:
  stage: test
  script:
    - echo "Запуск тестов для $APP_NAME"
    - echo "Время запуска $TIMESTAMP"

deploy:
  stage: deploy
  script:
    - echo "Деплой приложения $APP_NAME"
    - echo "Время деплоя $TIMESTAMP"
