stages:
  - prepare
  - build
  - test
  - deploy

include:
  - local: '.gitflic-ci2.yaml'

image: python:3.9

cache:
  key: my-cache-key
  paths:
    - venv/
    - .cache/pip

variables:
  ENVIRONMENT: production
  DEBUG: "false"

before_script:
  - echo "Setting up environment"
  - python -m venv venv
  - source venv/bin/activate

after_script:
  - echo "Cleanup"
  - deactivate

prepare:
  stage: prepare
  script:
    - echo "Preparing the environment"
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
    name: "prepare_artifacts"

build:
  stage: build
  script:
    - echo "Building the project"
    - python setup.py build
  artifacts:
    paths:
      - build/
    name: "build_artifacts"
    reports:
      junit: build/test-reports.xml
  needs: ["prepare"]

test:
  stage: test
  script:
    - echo "Running tests"
    - pytest --junitxml=build/test-reports.xml
  artifacts:
    paths:
      - build/test-reports.xml
  when: on_success
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      allow_failure: true

deploy:
  stage: deploy
  script:
    - echo "Deploying to $ENVIRONMENT"
    - echo "Running deployment script"
  tags:
    - deploy

trigger_deploy:
  stage: deploy
  trigger:
    project: mygroup/anotherproject
    branch: master
  tags:
    - deploy
  needs: ["deploy"]

