image: busybox:latest

stages:
  - build

build:
  stage: build
  script:
    - echo "Build"
    - mkdir -p test-reports
    - echo "Building" > test-reports/test-report.txt

test:
  stage: build
  script:
    - echo "Running tests"
  when: on_failure

