stages:
  - build
  - test
  - deploy


# Образ для выполнения задач
image: alpine:latest

# Этап тестирования
test_job:
  stage: test
  before_script:
    - echo "Setting up test environment"
  script:
    - echo "Running tests"
    - mkdir -p test-reports
    - echo "Test report content" > test-reports/test-report.txt
  artifacts:
    reports:
      paths:
      - spotbugsSarif.json


