# local-config.yaml

# Дополнительный этап
image: alpine:latest

extra_check_job:
  stage: test
  script:
    - echo "Running extra check"
    - mkdir -p extra-check
    - echo "Extra check result" > extra-check/check.txt
  artifacts:
    paths:
      - extra-check/
  tags:
    - test


