# local-config.yaml

# Дополнительный этап для дополнительной проверки
extra_check_job:
  stage: test
  script:
    - echo "Running extra check"
    - mkdir -p extra-check
    - echo "Extra check result" > extra-check/check.txt
  artifacts:
    paths:
      - extra-check/
    reports:
      junit: extra-check/test-results.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "master/*"'
      when: always
  tags:
    - test


